### PR TITLE
Fix for example plugin

### PR DESCRIPTION
**Pull request by prinzdezibel**
The example plugin had different bugs which were fixed:

- CartSubTotal is now a React component
- Route permissions are no longer maintained in Shop collection, but in Groups collection
- Header and Footer are now React components

Refactored:
- aboutUs view is now a React component

### CODE REVIEW

**Comment by prinzdezibel** [comment]
@zenweasel  I actually would retain the blue 'Debug bar' as it gives the developer a hint, what's going on under the hood.

**Comment by piizei** [comment]
I'm getting a following error from this branch:
Uncaught Error: Component 'Footer' not found. Use registerComponent to create it.
    at _replaceComponent (components.js:116)
    at footer.js (footer.js:17)

Footer.js  in the trace is the footer.js from this plugin.

I just did reaction init (with latest version of npm tool), and cloned this branch into imports/plugins/custom.

Am I doing something wrongly?

**Comment by prinzdezibel** [comment]
@piizei This PR depends on another PR (https://github.com/reactioncommerce/reaction/pull/3257) in core, which isn't approved yet.

**Review by brent-hoover — APPROVED** [review]
Tested. Verified fixed.

**Pull request merged**
