### PR TITLE
Fix for: Example plugin does not work with release-1.8.0

### PR DESCRIPTION
**Pull request by prinzdezibel**
Closes issue #28

Changes:
- use load-script to inject <script> element into document head
- Add package.json to project with load-script dependency
- Add node_modules to .gitignore
- Fix linting errors

### CODE REVIEW

**Comment by machikoyasuda** [comment]
Once this PR is QA'd and merged, we should tag and release it as `v.1.8.0`-compatible.

**Comment by Akarshit** [comment]
I will be creating a PR to make example-plugin compatible with `1.9.0`. That PR will have the contents of this PR.

**Comment by prinzdezibel** [comment]
@Akarshit  so this PR is obsolete now?

**Comment by spencern** [comment]
@Akarshit I'm closing this due to inactivity, but please reopen if it's still relevant.

**Pull request closed without merging**
